version: '3.8'
services:
  db:
    image: postgres:13.4
    container_name: postgres_container
    restart: always
    environment:
      - POSTGRES_USER=openvetuser
      - POSTGRES_PASSWORD=openvetpassword
      - POSTGRES_DB=openvetdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
